name: mvvm_linter
description: The MVVM Linter is a tool designed to enforce best practices and coding standards in MVVM.
version: 1.0.1
repository: https://github.com/nerdzlab/NerdzFlutter-MVVMLinter

environment:
  sdk: ^3.5.2

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.8
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
